-- ☕ COFFEE SALES DATABASE - SAMPLE DATA INSERTS
-- ================================================
-- Professional sample data for testing the ER schema
-- Generated by a senior dev who actually knows what good test data looks like

-- Clear existing data (if any)
DELETE FROM ventas;
DELETE FROM clientes;
DELETE FROM productos;
DELETE FROM metodos_pago;
DELETE FROM sucursales;

-- Reset auto-increment counters
DELETE FROM sqlite_sequence WHERE name IN ('clientes', 'productos', 'metodos_pago', 'sucursales', 'ventas');

-- ============================================================================
-- CLIENTES - Customer data with realistic anonymous codes and types
-- ============================================================================
INSERT INTO clientes (codigo_anonimo, tipo_cliente, fecha_primer_compra, fecha_ultima_compra, total_compras, monto_total_gastado, fecha_creacion) VALUES
('ANON_001', 'Regular', '2024-01-15', '2024-01-28', 8, 67.50, '2024-01-15 09:30:00'),
('ANON_002', 'Premium', '2024-01-10', '2024-01-30', 15, 125.75, '2024-01-10 14:22:00'),
('ANON_003', 'VIP', '2024-01-05', '2024-01-29', 25, 245.00, '2024-01-05 08:15:00'),
('ANON_004', 'Regular', '2024-01-20', '2024-01-25', 3, 28.50, '2024-01-20 16:45:00'),
('ANON_005', 'Premium', '2024-01-12', '2024-01-31', 12, 98.25, '2024-01-12 11:30:00'),
('ANON_006', 'Regular', '2024-01-18', '2024-01-26', 5, 42.75, '2024-01-18 13:20:00'),
('ANON_007', 'VIP', '2024-01-08', '2024-01-30', 18, 189.50, '2024-01-08 10:45:00'),
('ANON_008', 'Regular', '2024-01-22', '2024-01-27', 4, 35.00, '2024-01-22 15:10:00'),
('ANON_009', 'Premium', '2024-01-14', '2024-01-29', 9, 76.25, '2024-01-14 09:55:00'),
('ANON_010', 'Regular', '2024-01-16', '2024-01-28', 6, 51.50, '2024-01-16 12:40:00');

-- ============================================================================
-- PRODUCTOS - Coffee menu with realistic categories and pricing
-- ============================================================================
INSERT INTO productos (nombre_producto, categoria, precio_base, activo, fecha_creacion, fecha_actualizacion) VALUES
-- Bebidas Calientes
('Espresso', 'Bebida Caliente', 2.50, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Americano', 'Bebida Caliente', 3.00, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Cappuccino', 'Bebida Caliente', 4.00, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Latte', 'Bebida Caliente', 4.50, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Mocha', 'Bebida Caliente', 5.00, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Macchiato', 'Bebida Caliente', 4.25, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),

-- Bebidas Frías
('Iced Coffee', 'Bebida Fría', 3.50, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Frappuccino', 'Bebida Fría', 5.50, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Cold Brew', 'Bebida Fría', 4.00, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Iced Latte', 'Bebida Fría', 4.75, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),

-- Pasteles y Postres
('Croissant', 'Panadería', 3.25, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Muffin Arándanos', 'Panadería', 2.75, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Cheesecake', 'Postre', 4.50, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Brownie', 'Postre', 3.00, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Tiramisu', 'Postre', 5.25, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),

-- Snacks
('Sandwich Jamón', 'Snack', 6.50, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Bagel Crema', 'Snack', 4.25, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Ensalada Caesar', 'Snack', 8.75, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),

-- Productos Premium
('Café de Origen', 'Premium', 7.50, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
('Latte Dorado', 'Premium', 6.25, 1, '2024-01-01 00:00:00', '2024-01-01 00:00:00');

-- ============================================================================
-- METODOS_PAGO - Payment methods with descriptions and periods
-- ============================================================================
INSERT INTO metodos_pago (tipo_pago, descripcion, activo, periodo_dia) VALUES
('Efectivo', 'Pago en efectivo - billetes y monedas', 1, 'Todo el día'),
('Tarjeta Débito', 'Tarjeta de débito bancaria', 1, 'Todo el día'),
('Tarjeta Crédito', 'Tarjeta de crédito Visa/Mastercard', 1, 'Todo el día'),
('Transferencia', 'Transferencia bancaria móvil', 1, 'Todo el día'),
('PayPal', 'Pago digital PayPal', 1, 'Todo el día'),
('Apple Pay', 'Pago contactless Apple Pay', 1, 'Todo el día'),
('Google Pay', 'Pago contactless Google Pay', 1, 'Todo el día'),
('Cupón', 'Cupón de descuento o promoción', 1, 'Todo el día');

-- ============================================================================
-- SUCURSALES - Store locations with realistic addresses
-- ============================================================================
INSERT INTO sucursales (nombre_sucursal, direccion, ciudad, activa, fecha_apertura, fecha_creacion) VALUES
('Centro Histórico', 'Calle Principal 123', 'Ciudad Central', 1, '2023-06-15', '2023-06-01 00:00:00'),
('Mall Plaza Norte', 'Av. Los Andes 456, Local 23', 'Zona Norte', 1, '2023-08-20', '2023-08-01 00:00:00'),
('Campus Universitario', 'Universitaria 789', 'Zona Académica', 1, '2023-09-10', '2023-09-01 00:00:00'),
('Distrito Financiero', 'Torre Business Center, PB', 'Centro Financiero', 1, '2023-07-05', '2023-07-01 00:00:00'),
('Aeropuerto Internacional', 'Terminal 2, Sala de Embarque', 'Aeropuerto', 1, '2023-10-12', '2023-10-01 00:00:00'),
('Zona Rosa', 'Calle Bohemia 321', 'Distrito Cultural', 1, '2023-11-18', '2023-11-01 00:00:00');

-- ============================================================================
-- VENTAS - Sales transactions with realistic patterns and relationships
-- ============================================================================
INSERT INTO ventas (
    fecha_venta, fecha_hora_venta, hora_del_dia, 
    id_producto, id_metodo_pago, id_cliente, id_sucursal,
    precio_unitario, cantidad, monto_total,
    periodo_dia, dia_semana, nombre_mes,
    numero_dia_semana, numero_mes,
    fecha_creacion, fecha_actualizacion
) VALUES
-- Lunes matutino - Centro Histórico (rush matutino)
('2024-01-15', '2024-01-15 08:30:00', '08:30:00', 2, 1, 1, 1, 3.00, 1, 3.00, 'Mañana', 'Lunes', 'Enero', 1, 1, '2024-01-15 08:30:00', '2024-01-15 08:30:00'),
('2024-01-15', '2024-01-15 08:45:00', '08:45:00', 3, 2, 2, 1, 4.00, 2, 8.00, 'Mañana', 'Lunes', 'Enero', 1, 1, '2024-01-15 08:45:00', '2024-01-15 08:45:00'),
('2024-01-15', '2024-01-15 09:15:00', '09:15:00', 4, 3, 3, 1, 4.50, 1, 4.50, 'Mañana', 'Lunes', 'Enero', 1, 1, '2024-01-15 09:15:00', '2024-01-15 09:15:00'),
('2024-01-15', '2024-01-15 09:30:00', '09:30:00', 11, 1, NULL, 1, 3.25, 1, 3.25, 'Mañana', 'Lunes', 'Enero', 1, 1, '2024-01-15 09:30:00', '2024-01-15 09:30:00'),

-- Martes tarde - Mall Plaza Norte (familias y jóvenes)
('2024-01-16', '2024-01-16 14:20:00', '14:20:00', 8, 4, 4, 2, 5.50, 1, 5.50, 'Tarde', 'Martes', 'Enero', 2, 1, '2024-01-16 14:20:00', '2024-01-16 14:20:00'),
('2024-01-16', '2024-01-16 15:45:00', '15:45:00', 13, 2, 5, 2, 4.50, 1, 4.50, 'Tarde', 'Martes', 'Enero', 2, 1, '2024-01-16 15:45:00', '2024-01-16 15:45:00'),
('2024-01-16', '2024-01-16 16:10:00', '16:10:00', 7, 3, 6, 2, 3.50, 2, 7.00, 'Tarde', 'Martes', 'Enero', 2, 1, '2024-01-16 16:10:00', '2024-01-16 16:10:00'),

-- Miércoles - Campus Universitario (estudiantes)
('2024-01-17', '2024-01-17 10:30:00', '10:30:00', 2, 1, 7, 3, 3.00, 1, 3.00, 'Mañana', 'Miércoles', 'Enero', 3, 1, '2024-01-17 10:30:00', '2024-01-17 10:30:00'),
('2024-01-17', '2024-01-17 12:15:00', '12:15:00', 12, 5, 8, 3, 2.75, 1, 2.75, 'Tarde', 'Miércoles', 'Enero', 3, 1, '2024-01-17 12:15:00', '2024-01-17 12:15:00'),
('2024-01-17', '2024-01-17 15:40:00', '15:40:00', 9, 6, 9, 3, 4.00, 1, 4.00, 'Tarde', 'Miércoles', 'Enero', 3, 1, '2024-01-17 15:40:00', '2024-01-17 15:40:00'),

-- Jueves - Distrito Financiero (ejecutivos)
('2024-01-18', '2024-01-18 07:45:00', '07:45:00', 19, 3, 10, 4, 7.50, 1, 7.50, 'Mañana', 'Jueves', 'Enero', 4, 1, '2024-01-18 07:45:00', '2024-01-18 07:45:00'),
('2024-01-18', '2024-01-18 11:30:00', '11:30:00', 5, 2, 1, 4, 5.00, 1, 5.00, 'Mañana', 'Jueves', 'Enero', 4, 1, '2024-01-18 11:30:00', '2024-01-18 11:30:00'),
('2024-01-18', '2024-01-18 14:15:00', '14:15:00', 16, 4, 2, 4, 6.50, 1, 6.50, 'Tarde', 'Jueves', 'Enero', 4, 1, '2024-01-18 14:15:00', '2024-01-18 14:15:00'),

-- Viernes noche - Zona Rosa (vida nocturna)
('2024-01-19', '2024-01-19 19:20:00', '19:20:00', 15, 6, 3, 6, 5.25, 1, 5.25, 'Noche', 'Viernes', 'Enero', 5, 1, '2024-01-19 19:20:00', '2024-01-19 19:20:00'),
('2024-01-19', '2024-01-19 20:45:00', '20:45:00', 20, 7, 4, 6, 6.25, 1, 6.25, 'Noche', 'Viernes', 'Enero', 5, 1, '2024-01-19 20:45:00', '2024-01-19 20:45:00'),
('2024-01-19', '2024-01-19 21:10:00', '21:10:00', 6, 3, 5, 6, 4.25, 2, 8.50, 'Noche', 'Viernes', 'Enero', 5, 1, '2024-01-19 21:10:00', '2024-01-19 21:10:00'),

-- Sábado - Aeropuerto (viajeros)
('2024-01-20', '2024-01-20 06:30:00', '06:30:00', 1, 1, 6, 5, 2.50, 1, 2.50, 'Mañana', 'Sábado', 'Enero', 6, 1, '2024-01-20 06:30:00', '2024-01-20 06:30:00'),
('2024-01-20', '2024-01-20 13:45:00', '13:45:00', 10, 2, 7, 5, 4.75, 1, 4.75, 'Tarde', 'Sábado', 'Enero', 6, 1, '2024-01-20 13:45:00', '2024-01-20 13:45:00'),
('2024-01-20', '2024-01-20 17:20:00', '17:20:00', 14, 4, 8, 5, 3.00, 1, 3.00, 'Tarde', 'Sábado', 'Enero', 6, 1, '2024-01-20 17:20:00', '2024-01-20 17:20:00'),

-- Domingo familiar - Mall Plaza Norte
('2024-01-21', '2024-01-21 11:00:00', '11:00:00', 17, 3, 9, 2, 4.25, 1, 4.25, 'Mañana', 'Domingo', 'Enero', 0, 1, '2024-01-21 11:00:00', '2024-01-21 11:00:00'),
('2024-01-21', '2024-01-21 15:30:00', '15:30:00', 18, 5, 10, 2, 8.75, 1, 8.75, 'Tarde', 'Domingo', 'Enero', 0, 1, '2024-01-21 15:30:00', '2024-01-21 15:30:00'),

-- Más transacciones para completar el dataset
('2024-01-22', '2024-01-22 08:15:00', '08:15:00', 3, 1, 1, 1, 4.00, 1, 4.00, 'Mañana', 'Lunes', 'Enero', 1, 1, '2024-01-22 08:15:00', '2024-01-22 08:15:00'),
('2024-01-22', '2024-01-22 12:30:00', '12:30:00', 5, 2, 2, 3, 5.00, 1, 5.00, 'Tarde', 'Lunes', 'Enero', 1, 1, '2024-01-22 12:30:00', '2024-01-22 12:30:00'),
('2024-01-22', '2024-01-22 16:45:00', '16:45:00', 8, 3, 3, 2, 5.50, 1, 5.50, 'Tarde', 'Lunes', 'Enero', 1, 1, '2024-01-22 16:45:00', '2024-01-22 16:45:00'),
('2024-01-22', '2024-01-22 19:00:00', '19:00:00', 15, 4, NULL, 6, 5.25, 1, 5.25, 'Noche', 'Lunes', 'Enero', 1, 1, '2024-01-22 19:00:00', '2024-01-22 19:00:00'),

-- Transacciones adicionales para análisis más rico
('2024-01-23', '2024-01-23 09:20:00', '09:20:00', 4, 1, 4, 1, 4.50, 1, 4.50, 'Mañana', 'Martes', 'Enero', 2, 1, '2024-01-23 09:20:00', '2024-01-23 09:20:00'),
('2024-01-23', '2024-01-23 14:10:00', '14:10:00', 11, 5, 5, 4, 3.25, 2, 6.50, 'Tarde', 'Martes', 'Enero', 2, 1, '2024-01-23 14:10:00', '2024-01-23 14:10:00'),
('2024-01-23', '2024-01-23 18:35:00', '18:35:00', 20, 6, 6, 6, 6.25, 1, 6.25, 'Noche', 'Martes', 'Enero', 2, 1, '2024-01-23 18:35:00', '2024-01-23 18:35:00'),

-- Final batch para completar 30 transacciones
('2024-01-24', '2024-01-24 10:45:00', '10:45:00', 7, 7, 7, 3, 3.50, 1, 3.50, 'Mañana', 'Miércoles', 'Enero', 3, 1, '2024-01-24 10:45:00', '2024-01-24 10:45:00'),
('2024-01-24', '2024-01-24 13:20:00', '13:20:00', 16, 2, 8, 4, 6.50, 1, 6.50, 'Tarde', 'Miércoles', 'Enero', 3, 1, '2024-01-24 13:20:00', '2024-01-24 13:20:00'),
('2024-01-24', '2024-01-24 17:50:00', '17:50:00', 9, 3, 9, 5, 4.00, 1, 4.00, 'Tarde', 'Miércoles', 'Enero', 3, 1, '2024-01-24 17:50:00', '2024-01-24 17:50:00'),
('2024-01-24', '2024-01-24 20:15:00', '20:15:00', 19, 4, 10, 6, 7.50, 1, 7.50, 'Noche', 'Miércoles', 'Enero', 3, 1, '2024-01-24 20:15:00', '2024-01-24 20:15:00');

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Uncomment these to verify your data after insertion:

-- SELECT 'CLIENTES' as tabla, COUNT(*) as registros FROM clientes
-- UNION ALL
-- SELECT 'PRODUCTOS', COUNT(*) FROM productos
-- UNION ALL
-- SELECT 'METODOS_PAGO', COUNT(*) FROM metodos_pago
-- UNION ALL
-- SELECT 'SUCURSALES', COUNT(*) FROM sucursales
-- UNION ALL
-- SELECT 'VENTAS', COUNT(*) FROM ventas;

-- ============================================================================
-- SAMPLE ANALYSIS QUERIES
-- ============================================================================
-- Quick analysis to verify relationships work correctly:

-- Top selling products:
-- SELECT p.nombre_producto, COUNT(v.id_venta) as ventas, SUM(v.monto_total) as ingresos
-- FROM productos p
-- JOIN ventas v ON p.id_producto = v.id_producto
-- GROUP BY p.id_producto, p.nombre_producto
-- ORDER BY ingresos DESC
-- LIMIT 5;

-- Sales by store:
-- SELECT s.nombre_sucursal, COUNT(v.id_venta) as transacciones, SUM(v.monto_total) as ingresos
-- FROM sucursales s
-- JOIN ventas v ON s.id_sucursal = v.id_sucursal
-- GROUP BY s.id_sucursal, s.nombre_sucursal
-- ORDER BY ingresos DESC;

-- Client analysis:
-- SELECT c.codigo_anonimo, c.tipo_cliente, c.total_compras, c.monto_total_gastado
-- FROM clientes c
-- WHERE c.total_compras > 0
-- ORDER BY c.monto_total_gastado DESC;

-- ============================================================================
-- END OF SAMPLE DATA
-- ============================================================================